version: '3'
services:
  server:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - 9999:8080
    depends_on:
      cassandra:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./service
          target: /app
          ignore:
            - node_modules/
  cassandra:
    build:
      context: ./cassandra
      dockerfile: Dockerfile
    ports:
      - 9042:9042
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5